<?php //All Page ?>
<link rel="stylesheet" type="text/css" media="screen" href="css/all.css">

<?php //Page ?>
<link rel="stylesheet" type="text/css" media="screen" href="css/index.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/offre.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/blog.css">

<?php //Composant ?>
<link rel="stylesheet" type="text/css" media="screen" href="css/custombtn.css">
<script  src="javascript/navbar.js"></script>

