<?php if($page != 5){ ?>
<section id="contact">
    <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center desktop">
                    <p> Parlez-nous de votre projet <?php custombtn("form.php", "Contact", "white", "green"); ?></p>
                </div>

                <div class="col-md-12 text-center mobile">
                    <p style="padding-bottom: 12px;"> Parlez-nous de votre projet</p> <?php custombtn("form.php", "Contact", "white", "green"); ?>
                </div>
            </div>
        </div>
    </div>
</section>
<?php } ?>

<footer>


    <div id="foot-desktop" class="container align-items-center justify-content-between">
        <div id="logo1">
            <h5 class="widget-title">Certifications<span></span></h5>

            <img src="assets/certif/l1.png" style="width: 60px">

            <img src="assets/certif/l2.png" style="width: 60px">

            <img src="assets/certif/l4.jpg" style="width: 60px">
        </div>

        <h5 style="width: 50%; text-align: center">2022 © BâtirPositif<br><a href="legal.php"><j>Mentions Legales</j></a></h5>

        <div id="logo2">
            <h5 class="widget-title">Contact<span></span></h5>
            <?php


            $AllEnv = getAllEnv();

            foreach ($AllEnv as $EnvSection){
                if ($EnvSection['name'] == "mail"){ $SectionMail = $EnvSection; }
            }

            ?>
            <a href="mailto:<?php echo $SectionMail['content'] ?>"> <?php echo $SectionMail['content'] ?></a>

<!--            <p>0988415088</p>-->

            <ul class="social-footer2" style="margin-bottom: 10px; margin-top: 10px;">
                <li class=""><a title="Linkedin" target="_blank" href="https://www.linkedin.com/company/b%C3%A2tir-positif-ingenierie-responsable/"><img alt="Linkedin" width="30" height="30" src="https://tyrolium.fr/Contenu/Image/icone/linkedInWhite.png"></a></li>
                <li class=""><a title="Facebook" target="_blank" href="https://www.facebook.com/BatirPositif"><img alt="Facebook" width="30" height="30" src="https://tyrolium.fr/Contenu/Image/icone/facebookWhite.png"></a></li>
            </ul>
        </div>


    </div>

    <div id="foot-mobile" class=" align-items-center">

        <h5 style="text-align: center;
    padding: 18px 0px 40px 0px;">2022 © BâtirPositif<br><a href="legal.php"><j>Mentions Legales</j></a></h5>

        <div class="d-flex justify-content-between">
            <div id="logo" style="margin-left: 16px;">
                <h5 class="widget-title">Certifications<span></span></h5>

                <img src="assets/certif/l1.png" style="width: 60px">

                <img src="assets/certif/l2.png" style="width: 60px">

                <img src="assets/certif/l4.jpg" style="width: 60px">
            </div>


            <div style="
    margin-right: 16px;">
                <h5 class="widget-title">Contact<span></span></h5>

                <a href="mailto:contact@batirpositif.com">contact@batirpositif.com</a>

<!--                <p>0988415088</p>-->

                <ul class="social-footer2" style="margin-bottom: 10px; margin-top: 10px;">
                    <li class=""><a title="Linkedin" target="_blank" href="https://www.linkedin.com/company/b%C3%A2tir-positif-ingenierie-responsable/"><img alt="Linkedin" width="30" height="30" src="https://tyrolium.fr/Contenu/Image/icone/linkedInWhite.png"></a></li>
                    <li class=""><a title="Facebook" target="_blank" href="https://www.facebook.com/BatirPositif"><img alt="Facebook" width="30" height="30" src="https://tyrolium.fr/Contenu/Image/icone/facebookWhite.png"></a></li>
                </ul>
            </div>
        </div>


    </div>

</footer>

<style>



</style>