<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="Bâtir Positif">
<meta name="description" content="Site de Bâtir Positif - Ingenierie responsable"/>
<meta property="og:title" content="Bâtir Positif"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="https://batirpositif.com/"/>
<meta property="og:image" content="http://localhost/BatirPositif-WebSite/assets/LogoBatirPositif.png"/>
<meta property="og:description" content="Site de Bâtir Positif - Ingenierie responsable"/>