<header>
    <div class="header-banner" style="background-image: url('<?php echo $env_navImg; ?>');">
        <h1><img src="<?php echo $env_logoTransp; ?>"></h1>
    </div>
    <div class="clear"></div>
    <nav>
        <div class="site-title"><img src="<?php echo $env_logoTransp; ?>"></div>
        <ul>
            <li><a href="/test">page1</a></li>
            <li><a href="/test">page2</a></li>
            <li><a href="/test">page3</a></li>
        </ul>
    </nav>
</header>