<header id="nav-desktop">
    <!--<div class="header-banner" style="background-image: url('<?php /*echo $env_navImg; */?>');">
        <h1><img src="<?php /*echo $env_logoTransp; */?>"></h1>
    </div>-->

    <?php if($page == 1){ ?>
        <div class="clear"></div>
        <nav>
            <div class="site-title"><img src="<?php echo $env_logoTransp; ?>"></div>
            <ul class="center-ul">
                <?php

                $nbPage = count($env_page);

                for ($i = 1; $i <= 4; $i++) {

                    echo '<li';
                    if ($page == $i){
                        echo ' class="nav-active"';
                    }
                    echo '><a href="' . $env_page[$i]["file"] . '.php">' . $env_page[$i]["name"] . '</a></li>';

                }
                ?>
            </ul>
        </nav>
        <script src="javascript/navbar.js"></script>
    <?php } else { ?>
        <div class="clear"></div>
        <nav class="fixed-header">
            <div class="site-title visible-title"><a href="index.php"><img src="<?php echo $env_logoTransp; ?>"></a></div>
            <ul class="">
                <?php

                $nbPage = count($env_page);

                for ($i = 1; $i <= 4; $i++) {

                    echo '<li';
                    if ($page == $i){
                        echo ' class="nav-active"';
                    }
                    echo '><a href="' . $env_page[$i]["file"] . '.php">' . $env_page[$i]["name"] . '</a></li>';

                }
                ?>
            </ul>
        </nav>
    <?php } ?>
</header>

<header id="nav-mobile">
    <h1><img style="width: 155px;" src="<?php echo $env_logoTransp; ?>"></h1>

    <input id="burger" type="checkbox" />

    <label for="burger">
        <span></span>
        <span></span>
        <span></span>
    </label>

    <nav>
        <ul>

            <?php

            $nbPage = count($env_page);

            for ($i = 1; $i <= 4; $i++) {

                echo '<li';
                if ($page == $i){
                    echo ' class="nav-active"';
                }
                echo '><a href="' . $env_page[$i]["file"] . '.php">' . $env_page[$i]["name"] . '</a></li>';

            }
            ?>
        </ul>
    </nav>
</header>
